nome = str(input('Digite seu nome completo: ')).strip()
maiusculo = nome.upper()
print('Seu nome em maiúsculo é: {}'.format(maiusculo))
minusculo = nome.lower()
print('Seu nome minúsculo é: {}'.format(minusculo))
print('Seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
#p = int(nome.find(' '))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))
